### ISSUE TITLE
Multivalue bugs

### ISSUE THREAD

**Issue by santiagobadia** [gridap/GridapODEs.jl#10]
Hi @fverdugo 

I have been working on `MultiFieldFESpace` and time integration.

I have added a vector Laplacian and Stokes problem. I have been fixing bugs, but there is still a bug I cannot understand.

I think it is related to 
https://github.com/gridap/GridapODEs.jl/blob/c4c53ad55cc6c9816edd333ca5d17556b8a57ece/src/TransientFETools/TransientFEOperators.jl#L85-L104
but it is the same we have in `Gridap`.

If I uncomment the lines, the test
https://github.com/gridap/GridapODEs.jl/blob/master/test/TransientFEsTests/VectorHeatEquationTests.jl
does not work.

And in this version, multiple term operators do not work
https://github.com/gridap/GridapODEs.jl/blob/master/test/TransientFEsTests/TransientStokesEquationTests.jl

Can you take a look and let me know. I think we are very close to make all this work.

**Comment by fverdugo** [comment]
@santiagobadia I have fixed the problems in PR #12. Please, take a look to see what is going on an then merge.

The final check in the time-dependent stokes problem still fails, but this is provably related with the problem setup not with the library.

The first problem was related with some comments you have added marked as "hacks". 
I wonder if there is still some code in the library that you consider a hack? If yes, tell me and let's try to fix it.
