### ISSUE TITLE
zeromean not working

### ISSUE THREAD

**Issue by santiagobadia** [gridap/GridapODEs.jl#13]
@fverdugo I see that the `zeromean` related `FESpace` is not yet working, this part is missing.

https://github.com/gridap/GridapODEs.jl/blob/master/test/TransientFEsTests/TransientStokesEquationTests.jl

I remember you told me that there was a bug in `Gridap` for these spaces, not sure it will affect this development.

**Comment by fverdugo** [comment]
Try to replace all instances of `FEFunction` by `EvaluationFunction` in this file:

https://github.com/gridap/GridapODEs.jl/blob/master/src/TransientFETools/ODEOperatorInterfaces.jl

`EvaluationFunction` is specifically created to solve this issue. I think that I have already mentioned before, but we forgot to use it here.

**Comment by fverdugo** [comment]
By the way, `ZeroMeanFESpace` is not yet working in combination with `ExtendedFESpace` this is something I want to fix asap. Not related with this issue however.
