### ISSUE TITLE
Test Set

### ISSUE THREAD

**Issue by ConnorMallon** [gridap/GridapODEs.jl#56]
Is there a reason why not all of the tests are in the runtests.jl file?

i.e. there are 14 test in test/TransientFEsTests
      but only 11 tests in test/TransientFEsTests/runtests.jl

**Comment by ConnorMallon** [comment]
Hey @oriolcg, the autodiff tests are currently not included in the test set. Should these be working or is there more development required to get them working? For me, the ```StokesEquationAutoDiffTests.jl``` errors.

**Comment by oriolcg** [comment]
Hi @ConnorMallon, I updated the auto-diff part of `TransientFEOperators`  in the branch "[Fixing_autodiff](https://github.com/gridap/GridapODEs.jl/tree/Fixing_autodiff)". The Stokes test still doesn't work, but I think that the problem might be related to issue gridap/Gridap.jl#584. The other test that is not added is the ForwardEuler test, which I haven't had time to check where is the problem.

**Comment by ConnorMallon** [comment]
Ok I see, thanks Oriol :)
