### ISSUE TITLE
Example code solve bug

### ISSUE THREAD

**Issue by ThomasHaine** [gridap/GridapODEs.jl#60]
Running the example code in Julia 1.6.2 gives at the solve command:

`ERROR: LoadError: MethodError: no method matching solve(::ThetaMethod, ::GridapODEs.TransientFETools.TransientFEOperatorFromWeakForm{Nonlinear}, ::Gridap.FESpaces.SingleFieldFEFunction{Gridap.CellData.GenericCellField{ReferenceDomain}}, ::Float64, ::Float64)`

**Comment by oriolcg** [comment]
Thanks for reporting this error @ThomasHaine. It should be fixed in this PR #61, you can check the new README file here: https://github.com/gridap/GridapODEs.jl/blob/0e0cf3b027c43eb8e9cbfe9fec71279bffe1389d/README.md
