### ISSUE TITLE
Example code is not working

### ISSUE THREAD

**Issue by herveta** [gridap/GridapODEs.jl#67]
I launched the GridapODE example from the Github page, and it did not work... I got the following error (capy-pasted into a file, launched julia, included the file, and bim!). It seems the solver is not adapted, but I have trouble understanding where the problem really is.

julia> include("heat-dynamic_v0.jl")
ERROR: LoadError: MethodError: no method matching solve(::ThetaMethod, ::GridapODEs.TransientFETools.TransientFEOperatorFromWeakForm{Nonlinear}, ::Gridap.FESpaces.SingleFieldFEFunction{Gridap.CellData.GenericCellField{ReferenceDomain}}, ::Float64, ::Float64)
Closest candidates are:
  solve(::TransientFESolver, ::TransientFEOperator, ::Any, ::Real, ::Real) at /home/herve/.julia/packages/GridapODEs/8znve/src/TransientFETools/TransientFESolvers.jl:8
  solve(::TransientFESolver, ::TransientFEOperator, ::Any, ::Any, ::Any, ::Real, ::Real) at /home/herve/.julia/packages/GridapODEs/8znve/src/TransientFETools/TransientFESolvers.jl:13
  solve(::ODESolver, ::ODEOperator, ::T, ::Real, ::Real) where T at /home/herve/.julia/packages/GridapODEs/8znve/src/ODETools/ODESolvers.jl:30
Stacktrace:
 [1] top-level scope
   @ ~/Workspace/Julia/heat-dynamic_v0.jl:52
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [3] top-level scope
   @ REPL[1]:1
in expression starting at /home/herve/Workspace/Julia/heat-dynamic_v0.jl:52

**Comment by oriolcg** [comment]
Hi @herveta, which version of `GridapODEs` are you using? It should work with `GridapODEs@0.8.0`

**Comment by herveta** [comment]
> Hi @herveta, which version of `GridapODEs` are you using? It should work with `GridapODEs@0.8.0`

Thanks for your fast reply !
I use GridapODEs@0.7.0 with Julia 1.6.5 (which I chose because it is Long Term Support). I downloaded GridapODEs through the builtin package manager.

**Comment by herveta** [comment]
I activated GridapODEs 0.8.0 via an environment, and "Pkg.activate". Works fine. Seems like a simple operation (I learn Julia at the same time), I apologize for the issue. A warning for the example code with the reference version would be nice. 
Thank you
